{{- if and .Values.gui.enabled .Values.gui.useSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ if .Values.gui.secretName }}{{ .Values.gui.secretName }}{{ else }}{{ include "social-media-reuploader.fullname" . }}-gui-secret{{ end }}
type: Opaque
data:
  ADMIN_TOKEN: {{ .Values.env.ADMIN_TOKEN | default "" | b64enc | quote }}
  SECRET_KEY: {{ .Values.env.SECRET_KEY | default "" | b64enc | quote }}
  OAUTH_CLIENT_ID: {{ .Values.env.OAUTH_CLIENT_ID | default "" | b64enc | quote }}
  OAUTH_CLIENT_SECRET: {{ .Values.env.OAUTH_CLIENT_SECRET | default "" | b64enc | quote }}
  OAUTH_AUTHORIZE_URL: {{ .Values.env.OAUTH_AUTHORIZE_URL | default "" | b64enc | quote }}
  OAUTH_TOKEN_URL: {{ .Values.env.OAUTH_TOKEN_URL | default "" | b64enc | quote }}
  OAUTH_USERINFO_URL: {{ .Values.env.OAUTH_USERINFO_URL | default "" | b64enc | quote }}
{{- end -}}
