{{- if .Values.gui.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "social-media-reuploader.fullname" . }}-gui
  labels:
{{ include "social-media-reuploader.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.gui.port | default 8081 }}
      targetPort: {{ .Values.gui.port | default 8081 }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}
