{{- if and .Values.gui.enabled .Values.gui.useSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ if .Values.gui.secretName }}{{ .Values.gui.secretName }}{{ else }}{{ include "social-media-reuploader.fullname" . }}-gui-secret{{ end }}
type: Opaque
data:
  {{- if .Values.gui.secrets.adminToken }}
  ADMIN_TOKEN: {{ .Values.gui.secrets.adminToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.gui.secrets.secretKey }}
  SECRET_KEY: {{ .Values.gui.secrets.secretKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.gui.secrets.oauthClientId }}
  OAUTH_CLIENT_ID: {{ .Values.gui.secrets.oauthClientId | b64enc | quote }}
  {{- end }}
  {{- if .Values.gui.secrets.oauthClientSecret }}
  OAUTH_CLIENT_SECRET: {{ .Values.gui.secrets.oauthClientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.gui.secrets.oauthAuthorizeUrl }}
  OAUTH_AUTHORIZE_URL: {{ .Values.gui.secrets.oauthAuthorizeUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.gui.secrets.oauthTokenUrl }}
  OAUTH_TOKEN_URL: {{ .Values.gui.secrets.oauthTokenUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.gui.secrets.oauthUserinfoUrl }}
  OAUTH_USERINFO_URL: {{ .Values.gui.secrets.oauthUserinfoUrl | b64enc | quote }}
  {{- end }}
{{- end -}}
