{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{- if .Values.secret.name }}{{ .Values.secret.name }}{{- else }}{{ include "social-media-reuploader.fullname" . }}-secret{{- end }}
  labels:
{{ include "social-media-reuploader.labels" . | nindent 4 }}
type: Opaque
data:
  {{ default "BOT_TOKEN" .Values.secret.botTokenKey }}: {{ .Values.env.BOT_TOKEN | b64enc | quote }}
{{- end -}}
